### ISSUE TITLE
Cannot find module '/home/vagrant/how-to-sane/client/bower_components/ember/bower.json'

### ISSUE THREAD

**Issue by wayne-o** [mgenev/how-to-sane#1]
I don't seem to be able to get the how-to-sane app to run - after running npm install in both client and server I get 

Cannot find module '/home/vagrant/how-to-sane/client/bower_components/ember/bower.json'
client   | Error: Cannot find module '/home/vagrant/how-to-sane/client/bower_components/ember/bower.json'
client   |     at Function.Module._resolveFilename (module.js:338:15)
client   |     at Function.Module._load (module.js:280:25)
client   |     at Module.require (module.js:364:17)
client   |     at require (module.js:380:17)
client   |     at Class.module.exports.htmlbarsOptions (/home/vagrant/how-to-sane/client/node_modules/ember-cli-htmlbars/ember-addon-main.js:28:24)
client   |     at Object.app.registry.add.toTree (/home/vagrant/how-to-sane/client/node_modules/ember-cli-htmlbars/ember-addon-main.js:22:62)
client   |     at /home/vagrant/how-to-sane/client/node_modules/ember-cli/lib/preprocessors.js:104:26
client   |     at Array.forEach (native)
client   |     at processPlugins (/home/vagrant/how-to-sane/client/node_modules/ember-cli/lib/preprocessors.js:103:11)
client   |     at module.exports.preprocessTemplates (/home/vagrant/how-to-sane/client/node_modules/ember-cli/lib/preprocessors.js:86:10)

I have ran npm install --save bower in /client but it doesn't seem to fix it...

**Comment by DiknT** [comment]
bower is a package manager like npm, see bower.io. you need to install bower globally and then install the bower modules listed in bower.json in the client folder

    npm install -g bower
    rm -rf node_modules
    rm -rf bower_components
    npm install
    bower install

currently you also may have to adapt your package.json and bower.json because of the beta status. this works for me:
https://gist.github.com/DiknT/55db00f1e933e0daa648

**Comment by mgenev** [comment]
Thanks @DiknT  or the reply. @wayne-o was this sufficient?

**Comment by wayne-o** [comment]
Yes - thank you

On Tue, Jan 6, 2015 at 6:41 PM, Martin Genev <notifications@github.com>
wrote:

> Thanks @DiknT <https://github.com/DiknT> or the reply. @wayne-o
> <https://github.com/wayne-o> was this sufficient?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgenev/how-to-sane/issues/1#issuecomment-68910815>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*
