### ISSUE TITLE
sane up failed

### ISSUE THREAD

**Issue by feitian124** [mgenev/how-to-sane#16]
hi @mgenev, i followed the steps, very thing is fine but `sane up` failed and the error message is too simple for me to resolve, below is the error message.
```
✔ ~/work/how-to-sane [master|✔] 
22:59 $ sane up

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

the other steps is quite simple so should be fine, what is below step means?
```
Install imagemagic and graphicmagic like shown: https://github.com/aheckmann/gm
```

i'm using ubuntu, i installed both:
```
sudo apt-get install imagemagick graphicsmagick
```
then `sudo npm install -g gm`

 could you help? thank you.

**Comment by feitian124** [comment]
do i need fig installed?
i only have docker-compose.yml

**Comment by feitian124** [comment]
1. does `sane up` has some option to show more info? i checked `sane` seems not.
2. as `how-to-sane` aims to show user how to use sane, maybe we can add a script to check if all requirements are met?

**Comment by mgenev** [comment]
Can you please show the whole stack trace? I don't see the origin of the error.

**Comment by mgenev** [comment]
I personally don't run this with docker, fig shouldn't matter for sane up. Try running the server and the client separately from their folders and see which one breaks and what the whole stack trace is.

**Comment by IanVS** [comment]
@feitian124 You can try `sane up --verbose` to see if there is any extra logging.  There may not be, but it's worth a try.

As a note, you can `sane <command> --help` to get additional options for each command like up, generate, new, etc.

**Comment by feitian124** [comment]
@mgenev that is the whole stack trace. 
@IanVS tried `sane up --verbose`, the output the same.
when i running ther server and client separately, all seems fine but when i visit `http://localhost:4200/register` and filled the form then submit, there is 404 error:
`POST http://localhost:4200/api/v1/users 404 (Not Found)`

**Comment by IanVS** [comment]
@feitian124 Yes, when you `sane up` it runs `ember serve --proxy http://localhost:1337`

To try to isolate where the problem is, can you try running `sane up --skip-sails` and `sane up --skip-ember`?

**Comment by Globegitter** [comment]
@feitian124 @IanVS yeah the verbose flag really just shows extra stuff when you use docker on Mac/Windows. Otherwise everything that ember/sails prints should be printed.

And yep try `sane up --skip-sails` and `sane up --skip-ember` that is a good call. Also, which OS are you running? And which versions of node and sane-cli?

**Comment by feitian124** [comment]
hi @mgenev @Globegitter , today i tried `sane up` and it surprised me that very thing is ok now... 
then i recall that yesterday in order to run `ember server` in client folder, i installed `ember-cli` globally.
I try uninstall `ember-cli` then bingo, the err comes again.
I checked `sane` and `how-to-sane` document, there is no place mentioned a global installed `ember-cli` is required. 
can you confirm this is the root case? if so we need document it some where.

**Comment by IanVS** [comment]
What version of ember-cli did you install globally, and what is installed locally in your project?

Come to think of it, I've had problems in the past without having a globally installed ember-cli.  Will try to look into this tonight to see if I can figure out what's causing it.  I don't think the intent is to require global ember-cli.

**Comment by feitian124** [comment]
both the globally and locally are the latest version: "0.2.0-beta.1",

**Comment by Globegitter** [comment]
@feitian124 You may have discovered a bug - see https://github.com/artificialio/sane/issues/111

**Comment by Globegitter** [comment]
Since this is an issue with sane, we can close here.
