### ISSUE TITLE
Build and deploy

### ISSUE THREAD

**Issue by kedano** [mgenev/how-to-sane#18]
According to the sanestack docs a deploy should be posbile by running the following:

From the /client folder:

    ember build --environment=production --output-path=../server/assets/

And then from the /server folder

    node app.js

The issue is that the index.html file does not get served, you just get the unauthorised error message from the API.

With your example, should the client and the server be deployed decoupled?

**Comment by Globegitter** [comment]
@kedano Can you try to add here:  https://github.com/mgenev/how-to-sane/blob/master/server/config/policies.js#L37 

```js
AppController: {
  '*': true
}
```

and see if that fixes it?

**Comment by mgenev** [comment]
@kedano  I'm the pushing a fix, the problem was since I had only run this in dev mode, I had secured even the controller which serves the static, exactly like @Globegitter said :D try again with the latest and you'll be
