### ISSUE TITLE
failed test on client side

### ISSUE THREAD

**Issue by feitian124** [mgenev/how-to-sane#22]
frontend testing is a  headache for me but test is really important for a successful project.

hope we can fix the failed tests at client side.  http://localhost:4200/tests?nojshint

**Comment by mgenev** [comment]
i agree with you, i've been letting this sit, because at my workplace we are establishing a pattern to test with ember-cli which i was hoping to use here too, i'll take a look at these failures, we've had them all succeeding, but they keep breaking

**Comment by mgenev** [comment]
https://travis-ci.org/mgenev/how-to-sane

Now that you fixed the client tests, I added the web hook for travis and we're green for both client and server. Awesome! Now we just have to write some actual tests :D
