### ISSUE TITLE
sane up failed `can not find mkdirp`

### ISSUE THREAD

**Issue by feitian124** [mgenev/how-to-sane#34]
well, `sane up` seems failed to boot ember, the error message is below:

``` js
client   | Error: Cannot find module 'mkdirp'
client   |     at Function.Module._resolveFilename (module.js:336:15)
client   |     at Function.Module._load (module.js:278:25)
client   |     at Module.require (module.js:365:17)
client   |     at require (module.js:384:17)
client   |     at Object.<anonymous> (/home/ming/work/xrp/client/node_modules/ember-cli-less/node_modules/broccoli-less-single/index.js:3:14)
client   |     at Module._compile (module.js:460:26)
client   |     at Object.Module._extensions..js (module.js:478:10)
client   |     at Module.load (module.js:355:32)
client   |     at Function.Module._load (module.js:310:12)
client   |     at Module.require (module.js:365:17)
client   |     at require (module.js:384:17)
```

i'm not sure if it is same problem like #19 ?

**Comment by Globegitter** [comment]
No that is a different error and seems to me related to `ember-cli-less`. What happens if you run `ember s` in the `client` folder.

**Comment by mgenev** [comment]
Strange that the less module is erroring. I don't get that problem when I boot my server with `ember s` What system are you on @feitian124 ?

**Comment by feitian124** [comment]
@Globegitter the same problem.
i'm on ubuntu 14.10, node  0.12.2, npm 2.7.4

**Comment by mgenev** [comment]
hmm, i just tried a fresh ubuntu 14 and it seems working with `ember s`, i can't reproduce the problem...

**Comment by Globegitter** [comment]
@feitian124 did you try to delete your node_modules folder and `npm install` again in the client folder? Maybe npm just crapped out for some reason.
