### ISSUE TITLE
Loading gifs not found

### ISSUE THREAD

**Issue by krishnaglick** [mgenev/how-to-sane#38]
When uploading a photo, the system is unable to find some images.
/img/loading.gif
img/loading-sm.gif

There may be more. I believe this is in \how-to-sane\client\vendor\bootstrap-fileinput\fileinput.js:234 
Looks like bootstrap can't find the necessary files.

**Comment by mgenev** [comment]
thanks for opening the issue, i think they're being ignored by git, i'll fix that
