### ISSUE TITLE
Suggested packages "imagemagic" and "graphicmagic" actually called "imagemagick" and "graphicmagick".

### ISSUE THREAD

**Issue by StephanMeijer** [mgenev/how-to-sane#86]
Suggested packages "imagemagic" and "graphicmagic" actually called "imagemagick" and "graphicmagick" in the `README.md` file, located in the 'root' of the Git repository.

Please, update this file, and correct these two package names.

**Comment by mgenev** [comment]
Done, thanks for catching that.

**Comment by StephanMeijer** [comment]
Thanks for changing! Another suggestion:
Can you change `graphicmagick` to `graphicsmagick`?
