### ISSUE TITLE
Lots of errors on sane up and browsing localhost:4200 gives blank page

### ISSUE THREAD

**Issue by stevenchanin** [mgenev/how-to-sane#88]
I setup a brand new Ubuntu 14.04 64 bit environment to try this out. The exact setup steps are posted at: https://gist.github.com/stevenchanin/00cc81a8d308b13c52ca

At the very end, I cd into how-to-sane and do a `sane up` and get a bunch of error messages. When I try to browse `localhost:4200` I just see a blank screen.

A capture of the errors I get when I try to `sane up` is in: https://gist.github.com/stevenchanin/48f1a204bb27e715e6d5

**Comment by mgenev** [comment]
yes, this is because the project was developed for a while and then I added the linter and the errors haven't yet been cleared. I also use es7 which confuses linters. It's non breaking.

**Comment by stevenchanin** [comment]
Unfortunately, something is breaking for me. After doing the `sane up` if I try to hit `localhost:4200` the page is _totally blank._

The server isn't showing any logging in response to my GET against 4200. The page I see in my browser looks like:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Client</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/" />
<meta name="client/config/environment" content="%7B%22modulePrefix%22%3A%22client%22%2C%22podModulePrefix%22%3A%22client/pods%22%2C%22environment%22%3A%22development%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%22LOG_ACTIVE_GENERATION%22%3Atrue%2C%22LOG_VIEW_LOOKUPS%22%3Atrue%2C%22name%22%3A%22client%22%2C%22version%22%3A%220.0.0.cb763417%22%7D%2C%22contentSecurityPolicy%22%3A%7B%22default-src%22%3A%22%27self%27%20https%3A//maps.googleapis.com%22%2C%22font-src%22%3A%22*%22%2C%22connect-src%22%3A%22%27self%27%20https%3A//maps.googleapis.com%22%2C%22img-src%22%3A%22*%22%2C%22style-src%22%3A%22*%20%27unsafe-inline%27%22%2C%22frame-src%22%3A%22*%22%2C%22script-src%22%3A%22%27self%27%20%27unsafe-eval%27%20*.googleapis.com%20*.gstatic.com%22%2C%22media-src%22%3A%22%27self%27%22%7D%2C%22simple-auth%22%3A%7B%22authorizer%22%3A%22simple-auth-authorizer%3Aoauth2-bearer%22%7D%2C%22simple-auth-oauth2%22%3A%7B%22refreshAccessTokens%22%3Atrue%2C%22serverTokenEndpoint%22%3A%22/api/v1/auths/login%22%7D%2C%22contentSecurityPolicyHeader%22%3A%22Content-Security-Policy-Report-Only%22%2C%22flashMessageDefaults%22%3A%7B%22timeout%22%3A3000%2C%22priority%22%3A100%2C%22sticky%22%3Afalse%2C%22showProgress%22%3Afalse%2C%22type%22%3A%22info%22%2C%22types%22%3A%5B%22success%22%2C%22info%22%2C%22warning%22%2C%22danger%22%2C%22alert%22%2C%22secondary%22%5D%2C%22injectionFactories%22%3A%5B%22route%22%2C%22controller%22%2C%22view%22%2C%22component%22%5D%7D%2C%22exportApplicationGlobal%22%3Atrue%7D" />
<script src="/ember-cli-live-reload.js" type="text/javascript"></script>

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/client.css">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>


    
  </head>

  <body>
    
    <script type="text/javascript" charset="utf-8" src="runtime.js"> </script>
    <script src="assets/vendor.js"></script>
    <script src="assets/client.js"></script>

    
  </body>
</html>
```

**Comment by IanVS** [comment]
The breaking changes should now be addressed.  If you're still having problems, please reopen.

**Comment by stevenchanin** [comment]
It's still not working, but I get further now.

It went back in and did the following:
```
git pull
cd client
bower install
npm install
cd ../server
npm install
cd ..
sane up
```
now when I go to localhost:4200, I see the login page. If I client register, I see the registration page. However, trying to POST to either of these pages does not seem to do anything. After I submit, I'm left on the same page and no error is reported.

See https://gist.github.com/stevenchanin/c8402286e8d3b652b578/edit where I've copied what I see in the terminal and what I see in the browser console.

**Comment by IanVS** [comment]
This is a new issue, will track it in https://github.com/mgenev/how-to-sane/issues/91.
