### ISSUE TITLE
User data not sent in register request

### ISSUE THREAD

**Issue by IanVS** [mgenev/how-to-sane#91]
The user object is empty when submitting a request to create a new user.  This results in a 400 error from the server.

**Comment by stevenchanin** [comment]
Is there some log file that I should be looking at to see error messages? It feels really strange to observe it not working, but have no idea why and have no idea what to look at to understand more.

**Comment by IanVS** [comment]
The best place to look in these cases is in the dev tools of your browser.  For example, in chrome, I opened dev tools, then looked at the network tab to see the request which was being sent to the server.  In the payload, it showed that the `user` data it was sending was completely blank.  Then it was a matter of looking at the register route and template and figuring out why the data was not being sent.  In this case, it was because the template was using implicit creation of an objectController, upon which the user attributes were being set, but the ajax call sent to the server was pulling user attributes from the model.
