### ISSUE TITLE
How do you run npm install to properly get bcrypt?

### ISSUE THREAD

**Issue by maxscott** [mgenev/how-to-sane#92]
I'm currently running from boot2docker on my mac, and attempting to npm install on the image actually fails due to missing $PYTHON, which I can't seem to install, but isn't a part of the stock docker-sails image. Was wondering how you got around that, or if I'm just completely missing something.. Thanks!

**Comment by BransonGitomeh** [comment]
@maxwerr to properly get Bycrypt, my experience is that it works best with npm 0.10.x

**Comment by IanVS** [comment]
boot2docker is deprecated, and replaced with docker toolbox.  I'd suggest giving that a try and see if it helps.  I don't have a mac though, so I have no personal experience with it.

**Comment by kriswill** [comment]
You can also use a custom Dockerfile for your sails container.  for example:

``` Dockerfile
FROM iojs:3.2.0 

RUN mkdir -p /server \
  && npm install -g sails

VOLUME ["/server"]
WORKDIR /server
EXPOSE 1337
CMD ["sails", "lift"]
```

Then, in your `docker-compose.yml`:

``` yml
server:
  build: ./server
  volumes:
    - ./server/:/server
  ports:
    - "1337:1337"
  links:
    - db
```

Then to install the node modules _(from your sane root)_:

``` sh
→ docker-compose run server npm install
```

Any modules that are native in any dependency you are using will be compiled within the container, including bcrypt.

**Comment by maxscott** [comment]
re: @IanVS I see that now--the standard docker-sails image used in sane requires boot2docker though :( so maybe if I use the custom dockerfile as outlined by @kriswill !? Thanks for the tips :moneybag:
