### ISSUE TITLE
Question about best practices for sane-stack repo structure

### ISSUE THREAD

**Issue by maxscott** [mgenev/how-to-sane#93]
Is including both ember and sails apps And the residual sane files in the same repo the current best practice, just for the example, both, or negligible?

I ask because I would suspect any project of significant size or contributors could warrant separate repos, but it's unclear to me where fig/docker-compose/package.json/.sane-cli/.nvmrc/etc would go. Git submodules for the client and server?? :fearful:  

Thanks!
Max

**Comment by kriswill** [comment]
I like each application to be in separate repos, and I avoid submodules like the plague.  What I do generally is:

``` sh
> sane new blah
> cd blah
> mv client ../blah-client
> mv server ../blah-server
> ln -s ../blah-client client
> ln -s ../blah-server server
> git init
> cd client && git init
> cd ../server && git init
# set up remotes and push, etc
```

You will end up with 3 repos: "blah", "blah-client", "blah-server".  To onboard other developers, simply pull all 3 repos into the same dir, like:

``` sh
> cd ~/projects/
> git clone https://github.com/me/blah
> git clone https://github.com/me/blah-client
> git clone https://github.com/me/blah-server
```

add more client and server applications to taste.

**Comment by mgenev** [comment]
I agree with @kriswill in a real world situation, I would split them. For the sake of keeping this example in one place, they're together here

**Comment by maxscott** [comment]
Cool. I like the symlink solution--thanks!
